[launcher] Allow multiple Root of Trust in Agent
google/go-tpm-tools pull request #517
Opened 2024-12-21 02:08 UTC by jkl73

Launcher Attestatio Agent now can support multiple Root of Trust.
Extend operation will extend measurements to all RoTs.
Attest will generate quote/report on the "best" RoT.

2024-12-21 02:08 UTC, jkl73 commented
/gcbrun

2024-12-28 01:10 UTC, jkl73 commented
/gcbrun

2025-01-06 18:53 UTC, alexmwu requested changes
Not sure I understand this PR. I would have expected us to find all the roots we know about, loop through them, and extend each one with the same event. Potentially have a CEL for each type of root.

2025-01-06 18:53 UTC, alexmwu commented on launcher/agent/agent.go
> +// ordering matters, better root of trust must have a higher index
What constitutes a "better" rot?

2025-01-06 18:53 UTC, alexmwu commented on launcher/agent/agent.go
> +	aaarrr := a.getBestAttestRoot()
nit: ar or aRoot

2025-01-10 00:12 UTC, jkl73 commented
> Not sure I understand this PR. I would have expected us to find all the roots we know about, loop through them, and extend each one with the same event. Potentially have a CEL for each type of root.

Currently it will actively try to add `TPM` and `TDXRTMR`.
And yes, each root has it's own CEL, and will extend and record event to all roots.

2025-01-10 22:42 UTC, alexmwu commented on launcher/agent/agent.go
> +	if qp.IsSupported() == nil {
Here, we should create a list of roots of trust to measure to (e.g., `var measuredRots []attestRoot`) and then select the RTMR for the actual attestation verification root of trust (e.g., `avRot`).

```
var tpmAR := &tpmAttestRoot{...}
var measuredRots []*attestRoot
var avRot *attestRoot
// Check if VM is running TDX
...
if qp.IsSupported() == nil {
  tdxAR := &tdxAttestRoot
  measuredRots = append(measuredRots, tdxAR)
  avRot = tdxAr
} else {
  avRot = tpmAR
}
// Unconditionally add TPM.
measuredRots = append(measuredRots, tpmAR)
```

2025-01-10 23:13 UTC, jkl73 commented
/gcbrun

2025-01-13 18:36 UTC, alexmwu commented on launcher/agent/agent.go
> +
All of this is unused. Please remove.

2025-01-13 18:36 UTC, alexmwu commented on launcher/agent/agent.go
> +	GetType() rotType
This is also unused

2025-01-13 18:36 UTC, alexmwu commented on launcher/agent/agent.go
> +// Attest only attests to the "best" Attest Root.
nit: we should define how we select the attest root.
// When possible, Attest uses the technology-specific attestation root-of-trust and otherwise falls back to the vTPM.

2025-01-13 23:41 UTC, jkl73 commented on launcher/agent/agent.go
> +// Attest only attests to the "best" Attest Root.
done

2025-01-13 23:42 UTC, jkl73 commented on launcher/agent/agent.go
> +
deleted

2025-01-13 23:42 UTC, jkl73 commented on launcher/agent/agent.go
> +	GetType() rotType
deleted

2025-01-13 23:58 UTC, jkl73 commented on launcher/agent/agent.go
> +	if qp.IsSupported() == nil {
Done

2025-01-14 22:22 UTC, jkl73 commented
/gcbrun

2025-01-14 22:34 UTC, alexmwu approved these changes

2025-01-14 22:34 UTC, alexmwu commented on launcher/agent/agent.go
> +	// Get Canonical Event Log, The CEL should be consistent
", The CEL should be consistent"?

Maybe "GetCEL fetches the CEL with events corresponding to the sequence of `Extend`ed measurements attestation root."

2025-01-14 22:52 UTC, jkl73 commented on launcher/agent/agent.go
> +	// Get Canonical Event Log, The CEL should be consistent
yes, updated

2025-01-14 22:57 UTC, jkl73 commented
/gcbrun

2025-01-15 01:22 UTC, merged